const SUPABASE_URL=process.env.SUPABASE_URL||'';
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'';
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const WORLD_ID=process.env.TBG_WORLD_ID||'tbg-world-1';
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const bearer=(request)=>{const h=request.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7).trim():'';};
const isJwt=(v)=>String(v||'').split('.').length===3;
async function user(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,authorization:`Bearer ${token}`}});if(!r.ok)throw Object.assign(new Error('Session is invalid or expired'),{status:401});return r.json();}
async function rpc(name,body){const headers={apikey:SUPABASE_SERVICE_ROLE_KEY,'content-type':'application/json',accept:'application/json'};if(isJwt(SUPABASE_SERVICE_ROLE_KEY))headers.authorization=`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(result.message||result.error||`Supabase returned ${r.status}`),{status:r.status});return result;}
export default async(request)=>{try{if(!SUPABASE_URL||!SUPABASE_ANON_KEY||!SUPABASE_SERVICE_ROLE_KEY)return json({error:'Supabase is not configured'},503);const token=bearer(request);if(!token)return json({error:'Authentication required'},401);const auth=await user(token);if(request.method==='GET'){const result=await rpc('get_alpha_updates_for_user',{p_user_id:auth.id,p_world_id:WORLD_ID});if(!result?.ok)return json({error:result?.code||'Could not load alpha updates'},403);return json(result);}if(request.method==='POST'){const payload=await request.json().catch(()=>({}));if(payload.action!=='mark-read')return json({error:'Invalid action'},400);const result=await rpc('mark_alpha_update_read_for_user',{p_user_id:auth.id,p_update_id:payload.update_id,p_world_id:WORLD_ID});if(!result?.ok)return json({error:result?.code||'Could not mark update read'},400);return json(result);}return json({error:'Method not allowed'},405);}catch(error){return json({error:error.message},error.status||500);}};
